name: Python Lead Processing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  repository_dispatch:
    types: [lead]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install system dependencies 
        run: sudo apt-get install -y portaudio19-dev # keep as is 
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script to process initial leads
        run: python main.py
      - name: Install Gunicorn (for webhook server)
        run: pip install gunicorn
      - name: Run webhook server
        run: gunicorn webhook:app # Start the Flask app using Gunicorn
      - name: Upload logs (if failed)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-logs
          path: error.log # Adjust the path based on your logging setup
