name: Python Lead Processing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  repository_dispatch:
    types: [lead]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install system dependencies (if needed)
        run: sudo apt-get install -y portaudio19-dev

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script to process initial leads
        run: python main.py 

      - name: Install Gunicorn and Supervisord
        run: pip install gunicorn supervisor
 
      - name: Prepare Supervisord configuration
        run: |
          echo "[program:webhook]" >> supervisord.conf
          echo "command=gunicorn webhook:app --bind 0.0.0.0:5000" >> supervisord.conf
          echo "[supervisorctl]" >> supervisord.conf 
          echo "serverurl=http://127.0.0.1:9001" >> supervisord.conf  

      - name: Start webhook server with Supervisord
        run: supervisord -c supervisord.conf
       
      - name: Stop Supervisord
        run: supervisorctl -c supervisord.conf shutdown

      - name: Upload logs (if failed)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-logs
          path: error.log
