name: Python Lead Processing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  repository_dispatch:
    types: [lead]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install system dependencies 
        run: sudo apt-get install -y portaudio19-dev # Keep as is if needed
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script to process initial leads and start webhook server
        run: |
          python main.py &  # Run main.py in the background to process leads
          pip install gunicorn supervisor
          echo "[program:webhook]" >> supervisord.conf
          echo "command=gunicorn webhook:app" >> supervisord.conf
          supervisord -c supervisord.conf & # Run Supervisord in the background
      - name: Stop Supervisord
        run: |
          sleep 10
          supervisorctl shutdown # Gracefully shut down Supervisord and Gunicorn

